In [1]:
import sys, os
sys.path.insert(0, '../')
sys.path.insert(0, '../python_src/')

import numpy as np
import scipy as sp
import matplotlib as mpl
import matplotlib.pyplot as plt; plt.rcdefaults()
import seaborn as sns

import homology
import chomology

In [2]:
# NN = 5
# NE = 6

# edgei = [0, 0, 1, 2, 2, 3]
# edgej = [1, 2, 2, 3, 4, 4]

# f = [1, 2, 4, 3, 5, 0]

# NN = 2
# NE = 1

# edgei = [0]
# edgej = [1]

# f = [0]


NN = 4
NE = 4

edgei = [0, 0, 1, 2]
edgej = [3, 1, 2, 3]

f = [0, 2, 1, 3]

graph = chomology.Graph(NN, NE, edgei, edgej)

graph_comp = chomology.construct_graph_complex(graph, False)


for c in range(graph_comp.ncells):
        
    print(c, graph_comp.get_dim(c), graph_comp.get_label(c), graph_comp.get_facets(c))

    

0 0 0 []
1 0 1 []
2 0 2 []
3 0 3 []
4 1 0 [0, 3]
5 1 1 [0, 1]
6 1 2 [1, 2]
7 1 3 [2, 3]


In [3]:
filt_asc = chomology.construct_induced_filtration(graph_comp, f, 
                                                  np.argsort(np.argsort(f)), filt_dim=1, ascend=True)

print(filt_asc.get_filtration())

filt_desc = chomology.construct_induced_filtration(graph_comp, f, 
                                                  np.argsort(np.argsort(f)), filt_dim=1, ascend=False)

print(filt_desc.get_filtration())

[0, 3, 4, 1, 2, 6, 5, 7]
[2, 3, 7, 1, 0, 5, 6, 4]


In [4]:
V_asc, coV_asc = chomology.construct_discrete_gradient(filt_asc, graph_comp)

print(V_asc, coV_asc)


V_desc, coV_desc = chomology.construct_discrete_gradient(filt_desc, graph_comp)

print(V_desc, coV_desc)

[ 0  1  6  4 -1  5 -1  7] [ 0  1 -1 -1  3  5  2  7]
[ 5  1  2  7  4 -1  6 -1] [-1  1  2 -1  4  0  6  3]


In [5]:
ext_comp = chomology.extend_complex(graph_comp)

for c in range(ext_comp.ncells):
        
    print(c, ext_comp.get_dim(c), ext_comp.get_label(c), ext_comp.get_facets(c))

0 0 -1 []
1 0 0 []
2 0 1 []
3 0 2 []
4 0 3 []
5 1 4 [1, 4]
6 1 5 [1, 2]
7 1 6 [2, 3]
8 1 7 [3, 4]
9 1 0 [1, 0]
10 1 1 [2, 0]
11 1 2 [3, 0]
12 1 3 [4, 0]
13 2 4 [5, 9, 12]
14 2 5 [6, 9, 10]
15 2 6 [7, 10, 11]
16 2 7 [8, 11, 12]


In [6]:
ext_filt = chomology.extend_filtration(filt_asc, filt_desc, ext_comp)

print(filt_asc.get_filtration())
print(filt_desc.get_filtration())

print(ext_filt.get_filtration())


[0, 3, 4, 1, 2, 6, 5, 7]
[2, 3, 7, 1, 0, 5, 6, 4]
[0, 1, 4, 5, 2, 3, 7, 6, 8, 11, 12, 16, 10, 9, 14, 15, 13]


In [7]:
V, coV = chomology.extend_discrete_gradient(V_asc, V_desc, ext_comp)


print(V_asc, coV_asc)
print(V_desc, coV_desc)

print(V, coV)

[ 0  1  6  4 -1  5 -1  7] [ 0  1 -1 -1  3  5  2  7]
[ 5  1  2  7  4 -1  6 -1] [-1  1  2 -1  4  0  6  3]
[ 0  1  2  7  5 -1  6 -1  8 14 10 11 16 13 -1 15 -1] [ 0  1  2 -1 -1  4  6  3  8 -1 10 11 -1 13  9 15 12]


In [8]:
morse_comp = chomology.construct_morse_complex(V, ext_comp)

for c in range(morse_comp.ncells):
        
    print(c, morse_comp.get_dim(c), morse_comp.get_label(c), morse_comp.get_facets(c))
    
    
morse_filt = chomology.construct_morse_filtration(ext_filt, morse_comp)

print(morse_filt.get_filtration())

0 0 0 []
1 0 1 []
2 0 2 []
3 1 6 [2, 1]
4 1 8 [1, 2]
5 1 10 [0, 2]
6 1 11 [2, 0]
7 2 13 [4, 5, 6, 3]
8 2 15 [6, 5]
[0, 1, 2, 3, 4, 6, 5, 8, 7]


In [9]:
pairs = chomology.calc_persistence(ext_filt, ext_comp)

print(pairs)

for p in pairs:
    print(p, np.abs(ext_filt.get_func(p[0]) - ext_filt.get_func(p[1])))
    
    
mpairs = chomology.calc_persistence(morse_filt, morse_comp)

print(mpairs)

for p in mpairs:
    print(p, np.abs(morse_filt.get_func(p[0]) - morse_filt.get_func(p[1])))

[(4, 5), (3, 7), (2, 6), (1, 11), (12, 16), (9, 14), (10, 15), (8, 13)]
(4, 5) 0.0
(3, 7) 0.0
(2, 6) 1.0
(1, 11) 3.0
(12, 16) 0.0
(9, 14) 0.0
(10, 15) 1.0
(8, 13) 3.0
[(2, 3), (1, 6), (5, 8), (4, 7)]
(2, 3) 1.0
(1, 6) 3.0
(5, 8) 1.0
(4, 7) 3.0


In [10]:
basins = chomology.find_morse_basins(coV, morse_comp, ext_comp)

print(basins)

(basins, peaks) = chomology.find_morse_smale_basins(coV, morse_comp, ext_comp)

print("Basin", basins)

for b in basins:
    print(b, ext_comp.get_labels(basins[b]))

print("Peaks", peaks)

for p in peaks:
    print(p, ext_comp.get_labels(peaks[p]))
        
(skel_asc, skel_desc) = chomology.find_morse_smale_skeleton(mpairs, V, morse_comp, ext_comp)

print(skel_asc)
print(skel_desc)

{2: {2, 3}, 1: {1, 4}, 0: {0}}
Basin {2: {2, 3}, 1: {1, 4}}
2 {1, 2}
1 {0, 3}
Peaks {11: {11, 12}, 10: {9, 10}}
11 {2, 3}
10 {0, 1}
{6, 7}
{14, 15}


In [11]:
(threshold, pair) = chomology.find_join_feature([1, 2], V, coV, ext_filt, ext_comp, True)


print(threshold, pair)


morse_comp = chomology.construct_morse_complex(V, ext_comp)

for c in range(morse_comp.ncells):
        
    print(c, morse_comp.get_dim(c), morse_comp.get_label(c), morse_comp.get_facets(c))
    
    
chomology.simplify_morse_complex({pair}, V, coV, ext_filt, ext_comp, True)

# chomology.simplify_morse_complex(set(), V, coV, ext_filt, ext_comp, True)

morse_comp = chomology.construct_morse_complex(V, ext_comp)

for c in range(morse_comp.ncells):
        
    print(c, morse_comp.get_dim(c), morse_comp.get_label(c), morse_comp.get_facets(c))

Pass: 1
Unpaired Critical Cells: 9
Cancellable Pairs: 0
Pass: 2
Unpaired Critical Cells: 5
Cancellable Pairs: 1
1.0 (2, 6)
0 0 0 []
1 0 1 []
2 0 2 []
3 1 6 [2, 1]
4 1 8 [1, 2]
5 1 10 [0, 2]
6 1 11 [2, 0]
7 2 13 [4, 5, 6, 3]
8 2 15 [6, 5]
Pass: 1
Critical Cells: 9
Cancellable Pairs: 1
Cancelled Pairs: 1
Remaining Critical Cells: 7
Pass: 2
Critical Cells: 7
Cancellable Pairs: 1
Cancelled Pairs: 1
Remaining Critical Cells: 5
Pass: 3
Critical Cells: 5
Cancellable Pairs: 0
Cancelled Pairs: 0
Remaining Critical Cells: 5
0 0 0 []
1 0 1 []
2 0 2 []
3 1 6 [2, 1]
4 1 11 [2, 0]


In [12]:
print(V, coV)

[ 0  1  2  7  5 -1  6 -1 16 14 15 11 13 -1 -1 -1 -1] [ 0  1  2 -1 -1  4  6  3 -1 -1 -1 11 -1 12  9 10  8]


In [11]:
N = (ext_comp.ncells-1) / 2

asc_mskel = []
desc_mskel = []

for (i, j) in pairs:
    
    if morse_comp.get_dim(j) == 1 and morse_comp.get_label(i)-1 < N and morse_comp.get_label(j)-1 < N:
        print(j, morse_comp.get_label(j))
        
        asc_mskel.append(morse_comp.get_label(j))
        
    elif morse_comp.get_dim(j) == 2 and morse_comp.get_label(i)-1 >= N and morse_comp.get_label(j)-1 >= N:
        
        print(j, morse_comp.get_label(j))
        
        desc_mskel.append(morse_comp.get_label(j))
    
    
print(asc_mskel, desc_mskel)

4 9
[9] []


In [12]:
asc_skel = chomology.find_morse_features(asc_mskel, V, ext_comp)
desc_skel = chomology.find_morse_features(desc_mskel, V, ext_comp)

print(asc_skel)
print(desc_skel)

{9: {9, 7}}
{}
